### ISSUE TITLE
Stav webu https://zpevnik.skauting.cz/

### ISSUE THREAD

**Issue by lachmanfrantisek** [zpevnik/backend#1]
Ahoj,

všiml jsem tohohle projektu a zajímalo by mě, v jakém je stavu web https://zpevnik.skauting.cz/? -- Je očekávané, že zatím nejde zobrazovat písničky, ani je přidávat do zpěvníků? (Neměl jsem teď moc čas procházet kód a lokálně web nasadit.)

Systém by se mi hodil sice už na letošní tábor, ale klidně bych do budoucna přiložil ruku k dílu -- konečně nějaký skautský projekt v Pythonu..;-)

Franta

**Comment by kulikjak** [comment]
Ahoj,

moc se omlouvam - vubec jsem si tohoto nevsiml a ani mi neprisel mail ze se tu neco otevrelo, tak pisi alespon ted.

Momentalne jsme na tom tak, ze by to cele melo behat. Snazime se dovychytat posledni bugy (je to celkem dobre otestovane) a udelat celou aplikaci vice friendly a peknou - proste finishujici upravy. Take jsme to chteli vydat uz na tabor (uprimne puvodne jsme chteli uz tabor pred tim....), ale nejak se nam to protahuje. Nicmene ted uz skutecne finishujeme a na pristi to uz urcite bude :).

Lokalne by to tedy melo snad jit nasadit, nicmene ja doufam, ze treba do mesice (dvou) to uz pobezi na tom webu.

Kulda

**Comment by lachmanfrantisek** [comment]
Nazdar,

v pohodě. V nějaké volné chvilce se na to rád mrknu a zkusím rozchodit lokálně...

Ať se daří,
Franta
